export const REDUX = {
	CLEAR_DATA: 'CLEAR_DATA',

	//USER REDUCER
	LOG_IN: 'LOG_IN',
	LOG_OUT: 'LOG_OUT',
	GET_USER_INFO: 'GET_USER_INFO',
	UPDATE_USER_INFO: 'UPDATE_USER_INFO',
	UPDATE_ORDER_HISTORY: 'UPDATE_ORDER_HISTORY',
	UPDATE_COUPON_LIST: 'UPDATE_COUPON_LIST',

	//CART REDUCER
	ADD_TO_CART: 'ADD_TO_CART',
	REMOVE_FROM_CART: 'REMOVE_FROM_CART',
	UPDATE_ITEM: 'UPDATE_ITEM',
	CLEAR_CART: 'CLEAR_CART',
	UPDATE_PAYMENT_METHOD: 'UPDATE_PAYMENT_METHOD',
	UPDATE_SHIPPING_INFO: 'UPDATE_SHIPPING_INFO',

	//FAVORITE REDUCER
	ADD_TO_FAVORITE: 'ADD_TO_FAVORITE',
	REMOVE_FROM_FAVORITE: 'REMOVE_FROM_FAVORITE',
	//SHOP REDUCER
	LOADING: 'LOADING',
	LOAD_ERROR: 'LOAD_ERROR',
	LOAD_SUCCESS: 'LOAD_SUCCESS',
	UPDATE_SHOP_DATA: 'UPDATE_SHOP_DATA',
	CLEAR_SHOP_DATA: 'CLEAR_SHOP_DATA',
	UPDATE_SMART_PHONE_DATA: 'UPDATE_SMART_PHONE_DATA',
	UPDATE_LAPTOP_DATA: 'UPDATE_LAPTOP_DATA',
	UPDATE_TABLET_DATA: 'UPDATE_TABLET_DATA',
	UPDATE_ACCESSORIES_DATA: 'UPDATE_ACCESSORIES_DATA',
	UPDATE_FAVORITE_LIST: 'UPDATE_FAVORITE_LIST',
};
